apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"environment":"production","name":"api"},"name":"api"}}
  labels:
    environment: production
    kubernetes.io/metadata.name: api
    name: api
  name: api
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
